name: Continuous Integration
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: Android Build
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: "./gradlew assembleDebug"
